name: Pest tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.5
        ports:
          - 3306:3306
        env:
          MARIADB_DATABASE: activerendwerk_test
          MARIADB_USER: root
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: dom, json, pdo
          coverage: none

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci

      - name: Generated JS and CSS cache
        id: js-and-css-cache
        uses: actions/cache@v3
        with:
          path: public/build/**
          key: ${{ runner.os }}-js-and-css-${{ hashFiles('**/package-lock.json', '**/resources/{.js,scss}') }}

      - name: Generate front-end files
        if: steps.js-and-css-cache.outputs.cache-hit != 'true'
        run: npm run build

#      - name: Prepare Laravel environment
#        run: |
#          cp .env.github .env
#          php artisan key:generate
#          php artisan migrate --force
#          php artisan passport:keys

      - name: Run tests
        env:
          APP_URL: "http://activerendwerk.test"
        run: vendor/bin/pest
